# Generated by Django 4.0.4 on 2022-05-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_tag_lesson_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='tag',
        ),
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='courses.tag'),
        ),
    ]
